import fs from 'node:fs';

const VERSION = '0.3.23';
const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const assert = (condition, message) => {
  if (!condition) {
    console.error(`FAIL: ${message}`);
    process.exitCode = 1;
  }
};

const app = read('js/app.js');
const css = read('css/app.css');
const readerCss = read('css/reader.css');
const index = read('index.html');
const config = read('config.js');
const sw = read('sw.js');
const manifest = JSON.parse(read('manifest.webmanifest'));
const pkg = JSON.parse(read('package.json'));

assert(pkg.version === VERSION, 'package.json version');
assert(config.includes(`appVersion: '${VERSION}'`), 'config version');
assert(index.includes(`app.js?v=${VERSION}`), 'versioned app.js');
assert(index.includes(`app.css?v=${VERSION}`), 'versioned app.css');
assert(index.includes(`reader.css?v=${VERSION}`), 'versioned reader.css');
assert(sw.includes(`const APP_VERSION = '${VERSION}'`), 'service worker version');
assert(sw.includes('`./js/app.js?v=${APP_VERSION}`'), 'service worker precaches versioned JS');
assert(sw.includes('`./css/app.css?v=${APP_VERSION}`'), 'service worker precaches versioned CSS');
assert(sw.includes('`./css/reader.css?v=${APP_VERSION}`'), 'service worker precaches reader CSS');
assert(!css.includes('\\\\n') && !readerCss.includes('\\\\n'), 'CSS must not contain literal \\n sequences');
assert(!app.includes('LOCAL_RUNTIME_URLS'), 'no references to missing local vendor runtimes');
assert(app.includes("import('./modules/offline-webp.js')"), 'WebP offline module wired');
assert(index.includes('Content-Security-Policy'), 'CSP meta is present');
assert(index.includes('https://raw.githubusercontent.com'), 'CSP allows external raw GitHub PDF/cover assets');
assert(index.includes('keepZoomSelect'), 'keep zoom preference is present');
assert(app.includes('function zoomAtPoint'), 'point-centered zoom helper is present');
assert(app.includes('function flipbookLayoutClass'), 'flipbook single-page layout helper is present');
assert(app.includes('readerHistoryActive'), 'reader history integration is present');
assert(app.includes('verticalOffsetRatio'), 'vertical exact progress is present');
assert(app.includes('function ensureVerticalWindowLoaded'), 'vertical recovery window is present');
assert(app.includes('function verticalSlotNearViewport'), 'visible vertical slots are protected');
assert(app.includes("if (performanceProfile().mobile && !hasSavedReaderMode) state.mode = 'vertical';"), 'mobile defaults to vertical reading');
assert(app.includes('const caps = pdfRenderCaps(vertical, index);'), 'PDF fast-pass caps use base caps without recursion');
assert(app.includes('const caps = pdfRenderCapsForPass(vertical, index, fastPass);'), 'PDF renderer applies fast-pass caps');
assert(app.includes('function queuePagePrefetch'), 'controlled prefetch queue is present');
assert(app.includes('pageTransitioning'), 'page navigation coalescing is present');
assert(app.includes('fileUrl'), 'external PDF fileUrl support is present');
assert(index.includes(`config.js?v=${VERSION}`), 'versioned config.js');
assert(index.includes(`Manga-HQ-hub v${VERSION}`), 'visible title version');
assert(index.includes('external-acervo-2'), 'Acervo 2 source option is present');
assert(app.includes('function renderSourceOptions'), 'dynamic source selector is present');
assert(app.includes('Promise.all(jobs)'), 'external catalogs load in parallel');
assert(app.includes('failedSourceIds'), 'failed external source fallback is present');
assert(sw.includes('REMOTE_IMAGE_CACHE'), 'remote image cache is present');
assert(sw.includes('RAW_GITHUB_ORIGIN'), 'raw GitHub routing is present');
assert(index.includes('alphabetIndex'), 'alphabet navigation exists');
assert(app.includes('function jumpToCatalogLetter'), 'alphabet jump logic exists');
assert(app.includes('function renderAlphabeticalCards'), 'alphabet sections exist');
assert(app.includes("classList.toggle('mobile-fullbleed'"), 'mobile full-bleed reader is wired');
assert(readerCss.includes('.reader.mobile-fullbleed'), 'mobile full-bleed CSS exists');
assert(app.includes('function updateAlphabetFromScroll'), 'alphabet scroll tracking exists');
assert(app.includes('function setActiveAlphabetLetter'), 'alphabet active state exists');
assert(app.includes('function toggleReaderChrome'), 'reader chrome toggle exists');
assert(app.includes('function scheduleReaderChromeHide'), 'reader chrome auto-hide exists');
assert(readerCss.includes('.reader-chrome-hidden'), 'reader chrome hidden CSS exists');
assert(css.includes('.alphabet-btn.active'), 'active alphabet button CSS exists');
assert(index.includes('lowResModeSelect'), 'low resolution filter control exists');
assert(app.includes('function pageLooksLowResolution'), 'low resolution detection exists');
assert(app.includes('function applyLowResFilterToElement'), 'low resolution element filter exists');
assert(app.includes("lowRes:'auto'"), 'low resolution automatic default exists');
assert(readerCss.includes('.low-res-enhanced'), 'low resolution CSS exists');
assert(config.includes('Manga HQ Acervo Marvel'), 'Marvel source remains configured');
assert(index.includes('mobileReadingSelect'), 'mobile reading zoom control exists');
assert(app.includes('function mobileReadingScaleFor'), 'mobile reading scale logic exists');
assert(app.includes("mobileReading:'auto'"), 'mobile reading automatic default exists');
assert(app.includes('function applyMobileReadingScaleToSlot'), 'vertical mobile scaling exists');
assert(readerCss.includes('.mobile-reading-slot'), 'vertical mobile reading CSS exists');
assert(readerCss.includes('--reader-page-width'), 'paged mobile width override exists');
assert(index.includes('pdfQualitySelect'), 'PDF quality selector exists');
assert(app.includes('function pdfRenderCaps'), 'adaptive PDF render caps exist');
assert(app.includes('function applyPdfZoomPreview'), 'live PDF pinch preview exists');
assert(app.includes('function schedulePdfNeighborWarmup'), 'PDF neighbor warmup exists');
assert(app.includes('pdfVerticalTasks'), 'vertical PDF render task tracking exists');
assert(app.includes("pdfQuality:'auto'"), 'automatic PDF quality default exists');
assert(readerCss.includes('.pdf-pinch-preview'), 'PDF pinch preview CSS exists');
assert(app.includes('pdf-stage-staging'), 'staged PDF page swap exists');
assert(app.includes('function schedulePdfVerticalQualityUpgrade'), 'focused vertical PDF quality upgrade exists');
assert(app.includes("$('.page-slot').forEach(slot => state.verticalObserver.observe(slot))"), 'vertical slot iteration is correct');
assert(!app.split('\n').some(line => line.trim() === "$('.page-slot', root).forEach(slot => {"), 'vertical mobile scaling uses querySelectorAll helper');
assert(app.includes(`appVersion: '${VERSION}'`), 'internal app fallback version is current');
assert(readerCss.includes('.pdf-stage-staging'), 'PDF staging CSS exists');
assert(readerCss.includes('.reader.trim-margins.reader-mode-page'), 'PDF margin trimming CSS exists');
assert(readerCss.includes('.reader.trim-margins.reader-mode-vertical'), 'vertical PDF margin trimming exists');
assert(app.includes('RUNTIME_FALLBACK_URLS'), 'runtime fallback URLs exist');
assert(app.includes('async function importRuntime'), 'runtime import fallback helper exists');
assert(app.includes('memoryPressure'), 'memory pressure detection exists');
assert(app.includes('function renderPdfCanvasAttempt'), 'PDF render retry helper exists');
assert(app.includes('maxCanvasDimension'), 'PDF canvas dimension guard exists');
assert(app.includes("'IntersectionObserver' in window"), 'IntersectionObserver compatibility fallback exists');
assert(app.includes('displayRefreshRaf'), 'visual refresh batching exists');
assert(app.includes('createFolders:false'), 'JSZip avoids folder objects');
assert(!sw.includes('await cacheReaderRuntimes(cache);'), 'service worker does not eagerly download reader runtimes');
assert(app.includes('pagePending: new Map()'), 'in-flight page dedup map exists');
assert(app.includes('predecodedPages: new Map()'), 'predecoded page cache exists');
assert(app.includes('prefetchController: null'), 'prefetch abort controller state exists');
assert(app.includes('function predecodePage'), 'limited image predecode exists');
assert(app.includes('function clearPredecodedPages'), 'predecode cleanup exists');
assert(app.includes('state.prefetchController?.abort?.()'), 'prefetch aborts on reset');
assert(app.includes('existing?.archive === archive'), 'page extraction/download is deduplicated');
assert(app.includes("cache:'default'"), 'page manifests use browser cache');
assert(app.includes('const canStage = Boolean(oldStages.length'), 'image staging swap exists');
assert(app.includes("stage.style.visibility = 'hidden'"), 'staged images stay hidden until ready');
assert(app.includes("const images = scope?.matches?.('.page-stage') ? $$('img', scope) : $$('.page-stage img', scope || document);"), 'staged image wiring uses querySelectorAll helper');
assert(app.includes('progressSaveTimer: 0'), 'progress write batching state exists');
assert(app.includes('function flushProgressSave'), 'progress flush helper exists');
const openItemBlock = app.slice(app.indexOf('async function openItem('), app.indexOf('async function loadPdfJs', app.indexOf('async function openItem(')));
assert(openItemBlock.indexOf('flushProgressSave();') >= 0 && openItemBlock.indexOf('flushProgressSave();') < openItemBlock.indexOf('cleanupReaderData();'), 'progress flushes before reader cleanup when switching items');
assert(openItemBlock.includes('cleanupReaderData();'), 'item switching detaches the old reader synchronously');
assert(!openItemBlock.includes('await cleanupReaderData();'), 'item switching never waits for heavy cleanup');
const cleanupReaderBlock = app.slice(app.indexOf('function cleanupReaderData('), app.indexOf('function pushReaderHistoryEntry(', app.indexOf('function cleanupReaderData(')));
assert(cleanupReaderBlock.includes('const pdfDoc = state.pdfDoc;'), 'cleanup captures the old PDF document');
assert(cleanupReaderBlock.includes('state.pdfDoc = null;'), 'old PDF is detached from global state immediately');
assert(cleanupReaderBlock.includes('queueReaderCleanup({'), 'heavy reader resources are queued for background cleanup');
assert(app.includes('async function drainReaderCleanupQueue'), 'background cleanup queue exists');
assert(app.includes('requestIdleCallback(run, { timeout:1400 })'), 'heavy cleanup waits for an idle window');
assert(app.includes('pdfLoadingTask: null'), 'PDF loading task is tracked separately');
const openPdfBlock = app.slice(app.indexOf('async function openPdf('), app.indexOf('async function fetchArrayBufferWithProgress', app.indexOf('async function openPdf(')));
assert(openPdfBlock.includes('const pdfDoc = await task.promise;'), 'resolved PDF stays local until token validation');
assert(openPdfBlock.indexOf('if (token !== state.openToken)') < openPdfBlock.indexOf('state.pdfDoc = pdfDoc;'), 'stale PDF is rejected before touching active pdfDoc');
assert(app.includes('readerHistoryClosing'), 'pending history close state exists');
assert(app.includes('readerHistoryReopenPending'), 'rapid reopen history state exists');
assert(app.includes('function settleReaderHistoryClose'), 'history settle helper exists');
assert(app.includes('function schedulePdfMaintenance'), 'periodic PDF memory maintenance exists');
assert(app.includes('function schedulePdfPageQualityUpgrade'), 'mobile PDF fast-pass quality upgrade exists');
assert(app.includes('pdfVerticalWindow'), 'PDF vertical mode has a tighter RAM window');
assert(app.includes('function progressBucket'), 'progress bucket optimization exists');
assert(app.includes('document.elementFromPoint'), 'vertical current page uses viewport probe');
assert(app.includes('verticalLoaded: new Set()'), 'active vertical slot registry exists');
assert(app.includes('for (const i of [...state.verticalLoaded])'), 'vertical cleanup only scans active slots');
assert(app.includes('nextIssueCacheFor'), 'next issue lookup is cached');
assert(readerCss.includes('content-visibility:auto'), 'vertical content visibility optimization exists');
assert(index.includes('>Sair</button>'), 'reader exit button says Sair');
assert(index.includes('class="reader-close-btn reader-exit-btn"'), 'reader exit button class exists');
assert(app.includes("closeReader(false).catch"), 'exit button calls explicit normal close');
assert(app.includes('const triggeredByHistory = fromHistory === true'), 'close history flag is strict boolean');
assert(app.includes("reader.classList.add('hidden')"), 'reader hides before cleanup');
const closeReaderBlock = app.slice(app.indexOf('async function closeReader('), app.indexOf("window.addEventListener('popstate'", app.indexOf('async function closeReader(')));
assert(closeReaderBlock.indexOf("reader.classList.add('hidden')") >= 0 && closeReaderBlock.indexOf("reader.classList.add('hidden')") < closeReaderBlock.indexOf('cleanupReaderData();'), 'reader hides before resource detachment');
assert(closeReaderBlock.includes('scheduleLibraryRefreshAfterReaderClose();'), 'library rebuild is deferred after exit');
assert(!closeReaderBlock.includes('await cleanupReaderData();'), 'exit never waits for heavy cleanup');
assert(readerCss.includes('.reader-exit-btn'), 'reader exit button CSS exists');
assert(index.includes('id="closeReader"'), 'reader exit button exists');
assert(app.includes("closeReader(false).catch"), 'exit button calls normal close explicitly');
assert(app.includes("const triggeredByHistory = fromHistory === true"), 'history close flag uses strict boolean');
assert(readerCss.includes('.reader-exit-btn'), 'reader exit button styling exists');
assert(app.includes("history.scrollRestoration = 'manual'"), 'browser scroll restoration is disabled on boot');
assert(app.includes('function forceInitialHomeTop'), 'initial home top reset exists');
const alphabetSyncBlock = app.slice(app.indexOf('function updateAlphabetFromScroll'), app.indexOf('function scheduleAlphabetScrollSync', app.indexOf('function updateAlphabetFromScroll')));
assert(alphabetSyncBlock.includes("setActiveAlphabetLetter(current.dataset.alphaSection || '', false)"), 'passive alphabet sync never scrolls the page');
assert(index.includes('featuredCarouselDots'), 'featured carousel dots exist');
assert(index.includes('carouselPosition'), 'featured carousel position indicator exists');
assert(app.includes('function scheduleFeaturedCarouselAutoplay'), 'featured carousel autoplay exists');
assert(app.includes('function setFeaturedCarouselIndex'), 'featured carousel indexed navigation exists');
assert(app.includes('function pauseFeaturedCarousel'), 'featured carousel pauses on interaction');
assert(css.includes('.featured-card.is-active'), 'active featured card styling exists');
assert(css.includes('.carousel-dot.active'), 'carousel dot active styling exists');
assert(index.includes('recentSection'), 'recent additions rail exists');
assert(app.includes('function renderRecentArrivals'), 'recent additions rendering exists');
assert(index.includes('randomReadBtn'), 'random reading shortcut exists');
assert(app.includes('function openRandomLibraryItem'), 'random reading action exists');
assert(index.includes('exploreLibraryBtn'), 'explore catalog hero action exists');
assert(index.includes('id="libraryStickyHead"'), 'sticky library header wrapper exists');
assert(css.includes('.library-sticky-head{'), 'sticky library header CSS exists');
assert(css.includes('top:var(--library-sticky-top)'), 'sticky header follows topbar offset');
assert(css.includes('.mobile-filter-btn{display:none}'), 'mobile filter button is desktop-hidden');
assert(css.includes('.toolbar.mobile-filters-open #sourceSelect'), 'mobile filters expand on demand');
assert(app.includes('function updateLibraryStickyMetrics'), 'sticky header metrics are measured');
assert(app.includes('function libraryStickyScrollOffset'), 'alphabet jumps account for sticky header');
const alphaRevealBlock = app.slice(app.indexOf('function setActiveAlphabetLetter'), app.indexOf('let alphabetScrollRaf', app.indexOf('function setActiveAlphabetLetter')));
assert(!alphaRevealBlock.includes('scrollIntoView'), 'alphabet reveal only scrolls horizontally');
assert(alphaRevealBlock.includes('host.scrollTo'), 'alphabet reveal centers button horizontally');
assert(index.indexOf('id="libraryStickyHead"') < index.indexOf('id="continueSection"'), 'sticky header is before discovery rails');
assert(css.includes('.grid>.card{display:grid'), 'mobile horizontal card rule is scoped to main library grid');
assert(css.includes('.mini-card{\n    display:grid;\n    grid-template-columns:1fr;'), 'mobile universe cards stay vertical');
assert(css.includes('.universe-track::-webkit-scrollbar'), 'horizontal rail scrollbars are hidden');
assert(app.includes("const browsingHome = !state.collection && !state.search && state.filter === 'all' && !state.category;"), 'featured discovery hides during active search/filter');
assert(app.includes("const showHomeCategories = !state.collection && !state.search && state.filter === 'all';"), 'category discovery hides during search/filter');
assert(manifest.name === 'Manga-HQ-hub', 'PWA manifest name');

if (!process.exitCode) console.log('Smoke validation OK');
