import fs from 'node:fs';

const VERSION = '0.3.12';
const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const assert = (condition, message) => {
  if (!condition) {
    console.error(`FAIL: ${message}`);
    process.exitCode = 1;
  }
};

const app = read('js/app.js');
const css = read('css/app.css');
const readerCss = read('css/reader.css');
const index = read('index.html');
const config = read('config.js');
const sw = read('sw.js');
const manifest = JSON.parse(read('manifest.webmanifest'));
const pkg = JSON.parse(read('package.json'));

assert(pkg.version === VERSION, 'package.json version');
assert(config.includes(`appVersion: '${VERSION}'`), 'config version');
assert(index.includes(`app.js?v=${VERSION}`), 'versioned app.js');
assert(index.includes(`app.css?v=${VERSION}`), 'versioned app.css');
assert(index.includes(`reader.css?v=${VERSION}`), 'versioned reader.css');
assert(sw.includes(`const APP_VERSION = '${VERSION}'`), 'service worker version');
assert(sw.includes('`./js/app.js?v=${APP_VERSION}`'), 'service worker precaches versioned JS');
assert(sw.includes('`./css/app.css?v=${APP_VERSION}`'), 'service worker precaches versioned CSS');
assert(sw.includes('`./css/reader.css?v=${APP_VERSION}`'), 'service worker precaches reader CSS');
assert(!css.includes('\\\\n') && !readerCss.includes('\\\\n'), 'CSS must not contain literal \\n sequences');
assert(!app.includes('LOCAL_RUNTIME_URLS'), 'no references to missing local vendor runtimes');
assert(app.includes("import('./modules/offline-webp.js')"), 'WebP offline module wired');
assert(index.includes('Content-Security-Policy'), 'CSP meta is present');
assert(index.includes('https://raw.githubusercontent.com'), 'CSP allows external raw GitHub PDF/cover assets');
assert(index.includes('keepZoomSelect'), 'keep zoom preference is present');
assert(app.includes('function zoomAtPoint'), 'point-centered zoom helper is present');
assert(app.includes('function flipbookLayoutClass'), 'flipbook single-page layout helper is present');
assert(app.includes('readerHistoryActive'), 'reader history integration is present');
assert(app.includes('verticalOffsetRatio'), 'vertical exact progress is present');
assert(app.includes('function queuePagePrefetch'), 'controlled prefetch queue is present');
assert(app.includes('pageTransitioning'), 'page navigation coalescing is present');
assert(app.includes('fileUrl'), 'external PDF fileUrl support is present');
assert(index.includes(`config.js?v=${VERSION}`), 'versioned config.js');
assert(index.includes(`Manga-HQ-hub v${VERSION}`), 'visible title version');
assert(index.includes('external-acervo-2'), 'Acervo 2 source option is present');
assert(app.includes('function renderSourceOptions'), 'dynamic source selector is present');
assert(app.includes('Promise.all(jobs)'), 'external catalogs load in parallel');
assert(app.includes('failedSourceIds'), 'failed external source fallback is present');
assert(sw.includes('REMOTE_IMAGE_CACHE'), 'remote image cache is present');
assert(sw.includes('RAW_GITHUB_ORIGIN'), 'raw GitHub routing is present');
assert(index.includes('alphabetIndex'), 'alphabet navigation exists');
assert(app.includes('function jumpToCatalogLetter'), 'alphabet jump logic exists');
assert(app.includes('function renderAlphabeticalCards'), 'alphabet sections exist');
assert(app.includes("classList.toggle('mobile-fullbleed'"), 'mobile full-bleed reader is wired');
assert(readerCss.includes('.reader.mobile-fullbleed'), 'mobile full-bleed CSS exists');
assert(app.includes('function updateAlphabetFromScroll'), 'alphabet scroll tracking exists');
assert(app.includes('function setActiveAlphabetLetter'), 'alphabet active state exists');
assert(app.includes('function toggleReaderChrome'), 'reader chrome toggle exists');
assert(app.includes('function scheduleReaderChromeHide'), 'reader chrome auto-hide exists');
assert(readerCss.includes('.reader-chrome-hidden'), 'reader chrome hidden CSS exists');
assert(css.includes('.alphabet-btn.active'), 'active alphabet button CSS exists');
assert(index.includes('lowResModeSelect'), 'low resolution filter control exists');
assert(app.includes('function pageLooksLowResolution'), 'low resolution detection exists');
assert(app.includes('function applyLowResFilterToElement'), 'low resolution element filter exists');
assert(app.includes("lowRes:'auto'"), 'low resolution automatic default exists');
assert(readerCss.includes('.low-res-enhanced'), 'low resolution CSS exists');
assert(config.includes('Manga HQ Acervo Marvel'), 'Marvel source remains configured');
assert(index.includes('mobileReadingSelect'), 'mobile reading zoom control exists');
assert(app.includes('function mobileReadingScaleFor'), 'mobile reading scale logic exists');
assert(app.includes("mobileReading:'auto'"), 'mobile reading automatic default exists');
assert(app.includes('function applyMobileReadingScaleToSlot'), 'vertical mobile scaling exists');
assert(readerCss.includes('.mobile-reading-slot'), 'vertical mobile reading CSS exists');
assert(readerCss.includes('--reader-page-width'), 'paged mobile width override exists');
assert(index.includes('pdfQualitySelect'), 'PDF quality selector exists');
assert(app.includes('function pdfRenderCaps'), 'adaptive PDF render caps exist');
assert(app.includes('function applyPdfZoomPreview'), 'live PDF pinch preview exists');
assert(app.includes('function schedulePdfNeighborWarmup'), 'PDF neighbor warmup exists');
assert(app.includes('pdfVerticalTasks'), 'vertical PDF render task tracking exists');
assert(app.includes("pdfQuality:'auto'"), 'automatic PDF quality default exists');
assert(readerCss.includes('.pdf-pinch-preview'), 'PDF pinch preview CSS exists');
assert(app.includes('pdf-stage-staging'), 'staged PDF page swap exists');
assert(app.includes('function schedulePdfVerticalQualityUpgrade'), 'focused vertical PDF quality upgrade exists');
assert(app.includes("for (const slot of $('.page-slot'))"), 'vertical slot iteration is correct');
assert(readerCss.includes('.pdf-stage-staging'), 'PDF staging CSS exists');
assert(readerCss.includes('.reader.trim-margins.reader-mode-page'), 'PDF margin trimming CSS exists');
assert(readerCss.includes('.reader.trim-margins.reader-mode-vertical'), 'vertical PDF margin trimming exists');
assert(manifest.name === 'Manga-HQ-hub', 'PWA manifest name');

if (!process.exitCode) console.log('Smoke validation OK');
